### ISSUE TITLE
The plugin should crash when no applicationIdAppName was provided.

### ISSUE THREAD

**Issue by vanlooverenkoen** [Chimerapps/gradle-appcenter-android-plugin#1]
https://github.com/Chimerapps/gradle-appcenter-android-plugin/blob/7bca789b7725a5b66e6517d3b0c97e3d9fdbfc91/src/main/kotlin/com/chimerapps/gradle/GradpleAppcenterPlugin.kt#L38

When no applicationIdToAppName is provided. The plugin will not be configured. And will only log a debug statement. 

I think when nothing is provided the plugin should not be used at all and an error should be thrown.

**Comment by vanlooverenkoen** [comment]
it seems that variantToAppName is required even if I specified the applicationIdToAppName?

**Comment by NicolaVerbeeck** [comment]
This skips adding the uploadToAppcenter for that given variant, it makes sense for example to skip creating tasks for debug builds. If the plugin would stop the build when some variants are not mapped, ...
